import { StyleRules } from './types';
import { AccordionClasses } from '../components/Accordion/index';
import { AvatarClasses } from '../components/Avatar/index';
import { AppBarClasses } from '../components/AppBar/index';
import { BrandClasses } from '../components/Brand/index';
import { ButtonClasses } from '../components/Button/index';
import { ButtonBaseClasses } from '../components/ButtonBase/index';
import { ButtonGroupClasses } from '../components/ButtonGroup/index';
import { CardClasses } from '../components/Card/index';
import { CardActionAreaClasses } from '../components/CardActionArea/index';
import { CardActionsClasses } from '../components/CardActions/index';
import { CardContentClasses } from '../components/CardContent/index';
import { CardHeaderClasses } from '../components/CardHeader/index';
import { CardMediaClasses } from '../components/CardMedia/index';
import { ChipClasses } from '../components/Chip/index';
import { CircularProgressClasses } from '../components/CircularProgress/index';
import { ClickAwayListenerClasses } from '../components/ClickAwayListener/index';
import { ContainerClasses } from '../components/Container/index';
import { DialogClasses } from '../components/Dialog/index';
import { DividerClasses } from '../components/Divider/index';
import { DrawerClasses } from '../components/Drawer/index';
import { FlexClasses } from '../components/Flex/index';
import { FlexChildClasses } from '../components/FlexChild/index';
import { HiddenClasses } from '../components/Hidden/index';
import { IconClasses } from '../components/Icon/index';
import { IconButtonClasses } from '../components/IconButton/index';
import { ImageClasses } from '../components/Image/index';
import { LinearProgressClasses } from '../components/LinearProgress/index';
import { LineClampClasses } from '../components/LineClamp/index';
import { LinkClasses } from '../components/Link/index';
import { MenuClasses } from '../components/Menu/index';
import { MenuItemClasses } from '../components/MenuItem/index';
import { MenuListClasses } from '../components/MenuList/index';
import { MenuListItemClasses } from '../components/MenuListItem/index';
import { PaginationClasses } from '../components/Pagination/index';
import { PaperClasses } from '../components/Paper/index';
import { PortalClasses } from '../components/Portal/index';
import { ResponsiveImageClasses } from '../components/ResponsiveImage/index';
import { RippleClasses } from '../components/Ripple/index';
import { RouterLinkClasses } from '../components/RouterLink/index';
import { SashClasses } from '../components/Sash/index';
import { ScrimClasses } from '../components/Scrim/index';
import { SvgIconClasses } from '../components/SvgIcon/index';
import { StepClasses } from '../components/Step/index';
import { StepperClasses } from '../components/Stepper/index';
import { TabClasses } from '../components/Tab/index';
import { TableClasses } from '../components/Table/index';
import { TableBodyClasses } from '../components/TableBody/index';
import { TableCellClasses } from '../components/TableCell/index';
import { TableContainerClasses } from '../components/TableContainer/index';
import { TableFootClasses } from '../components/TableFoot/index';
import { TableHeadClasses } from '../components/TableHead/index';
import { TablePaginationClasses } from '../components/TablePagination/index';
import { TableRowClasses } from '../components/TableRow/index';
import { TableSortLabelClasses } from '../components/TableSortLabel/index';
import { TabPanelClasses } from '../components/TabPanel/index';
import { TabsClasses } from '../components/Tabs/index';
import { TypographyClasses } from '../components/Typography/index';

export type Overrides = {
  [Name in keyof ComponentNameToClasses]?: Partial<StyleRules<ComponentNameToClasses[Name]>>;
};

export interface ComponentNameToClasses {
  Accordion: AccordionClasses;
  AppBar: AppBarClasses;
  Avatar: AvatarClasses;
  Brand: BrandClasses;
  Button: ButtonClasses;
  ButtonBase: ButtonBaseClasses;
  ButtonGroup: ButtonGroupClasses;
  Card: CardClasses;
  CardActionArea: CardActionAreaClasses;
  CardActions: CardActionsClasses;
  CardContent: CardContentClasses;
  CardHeader: CardHeaderClasses;
  CardMedia: CardMediaClasses;
  Chip: ChipClasses;
  CircularProgress: CircularProgressClasses;
  ClickAwayListener: ClickAwayListenerClasses;
  Container: ContainerClasses;
  Dialog: DialogClasses;
  Divider: DividerClasses;
  Drawer: DrawerClasses;
  Flex: FlexClasses;
  FlexChild: FlexChildClasses;
  Hidden: HiddenClasses;
  Icon: IconClasses;
  IconButton: IconButtonClasses;
  LinearProgress: LinearProgressClasses;
  LineClamp: LineClampClasses;
  Link: LinkClasses;
  Image: ImageClasses;
  Menu: MenuClasses;
  MenuItem: MenuItemClasses;
  MenuList: MenuListClasses;
  MenuListItem: MenuListItemClasses;
  Pagination: PaginationClasses;
  Paper: PaperClasses;
  Portal: PortalClasses;
  ResponsiveImage: ResponsiveImageClasses;
  Ripple: RippleClasses;
  RouterLink: RouterLinkClasses;
  Sash: SashClasses;
  Scrim: ScrimClasses;
  Step: StepClasses;
  Stepper: StepperClasses;
  SvgIcon: SvgIconClasses;
  Tab: TabClasses;
  Table: TableClasses;
  TableBody: TableBodyClasses;
  TableCell: TableCellClasses;
  TableContainer: TableContainerClasses;
  TableFoot: TableFootClasses;
  TableHeader: TableHeadClasses;
  TablePagination: TablePaginationClasses;
  TableRow: TableRowClasses;
  TableSortLabel: TableSortLabelClasses;
  TabPanel: TabPanelClasses;
  Tabs: TabsClasses;
  Typography: TypographyClasses;
}
