export const FontFamiliesPoppins : string;
export const FontFamiliesOpenSans : string;
export const LineHeights0 : string;
export const LineHeights1 : string;
export const LineHeights2 : string;
export const LineHeights3 : string;
export const LineHeights4 : string;
export const LineHeights5 : string;
export const LineHeights6 : string;
export const FontWeightsPoppins0 : string;
export const FontWeightsPoppins1 : string;
export const FontWeightsPoppins2 : string;
export const FontWeightsPoppins3 : string;
export const FontWeightsPoppins4 : string;
export const FontWeightsOpenSans5 : string;
export const FontWeightsOpenSans6 : string;
export const FontSize0 : number;
export const FontSize1 : number;
export const FontSize2 : number;
export const FontSize3 : number;
export const FontSize4 : number;
export const FontSize5 : number;
export const FontSize6 : number;
export const LetterSpacing0 : number;
export const ParagraphSpacing0 : number;
export const ParagraphSpacing1 : number;
export const ParagraphSpacing2 : number;
export const Display400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Display700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H1200 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H1600 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H1700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H1200Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H1600Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H2400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H2600 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H2700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H3400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H3500 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H3600 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H3700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H3400Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H3600Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H4400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H4500 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H4600 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H4700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H4400Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H4600Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H5400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H5500 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H5600 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H5700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H5400Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H5600Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H6400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H6500 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H6600 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H6700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H6400Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const H6600Title : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const P400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const P700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const PSmall400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const PSmall700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Helper400 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Helper700 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, textCase: string, textDecoration: string };
export const TextCaseNone : string;
export const TextCaseCapitalize : string;
export const TextDecorationNone : string;
export const Grey50 : string;
export const Grey100 : string;
export const Grey200 : string;
export const Grey300 : string;
export const Grey400 : string;
export const Grey500 : string;
export const Grey600 : string;
export const Grey700 : string;
export const Grey800 : string;
export const Grey900 : string;
export const GreyBlack : string;
export const GreyWhite : string;
export const PrimaryDark : string;
export const PrimaryDefault : string;
export const PrimaryHover : string;
export const PrimaryLight : string;
export const SecondaryDark : string;
export const SecondaryDefault : string;
export const SecondaryHover : string;
export const SecondaryLight : string;
export const TextPrimary : string;
export const TextSecondary : string;
export const TextHint : string;
export const TextHint2 : string;
export const TextDisabled : string;
export const TextContrast : string;
export const SuccessDark : string;
export const SuccessDefault : string;
export const SuccessHover : string;
export const SuccessLight : string;
export const ErrorDark : string;
export const ErrorDefault : string;
export const ErrorHover : string;
export const ErrorLight : string;
export const ErrorDefaultScreen : string;
export const WarningDark : string;
export const WarningDefault : string;
export const WarningHover : string;
export const WarningLight : string;
export const WarningDefaultScreen : string;
export const InfoDark : string;
export const InfoDefault : string;
export const InfoHover : string;
export const InfoLight : string;
export const Background50 : string;
export const Background100 : string;
export const Background900 : string;
export const BackgroundWhite : string;
export const BackgroundBlack : string;
export const BackgroundDisabled : string;
export const BackgroundScrim : string;
export const HoverGreyHoverLight : string;
export const HoverGreyHoverMed : string;
export const HoverGreyHoverDark : string;
export const OuterEl1 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl2 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl3 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl4 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl5 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl6 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl7 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl8 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl9 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl10 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl11 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl12 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl13 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl14 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl15 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl16 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl17 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl18 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl19 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl20 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl21 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl22 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl23 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const OuterEl24 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const R4 : string;
export const R8 : string;
export const R16 : string;
export const R24 : string;
export const R32 : string;
export const R1000 : string;
export const InnerTop335 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const InnerCenter210 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const InnerCenter230 : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GradientsPrimary0 : string;
export const GradientsPrimary45 : string;
export const ComponentEl0SwitchKnob : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl1Fab : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl2SearchDefault : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl3ToolTip : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl3FilterDrawer : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl4Pills : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl4SearchActive : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl4MainNav : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl4Menus : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl8Inputs : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl8DataTable : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const ComponentEl8Alerts : { color: string, type: string, x: number, y: number, blur: number, spread: number };