name: merge changes into downstream branches

on:
  push:
    branches:
      - 'main'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # checks out out repo to $GITHUB_WORKSPACE
      # note: this has to be a full clone to avoid "fatal: refusing to merge unrelated histories"
      - uses: actions/checkout@v1
      - uses: opensesame/Actions/merge@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
