name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Terraform Apply to Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: terraform/
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.11

      - name: Get AWS Credentials
        id: get-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.FACELESS_ROLE_ARN }}
          role-duration-seconds: 900

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Github Credentials
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo '${{ secrets.ORG_READ_ONLY_SSH_KEY  }}' > ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color
